### ISSUE TITLE
[Docs]: Improve the documentation landing page

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#1136]
### Describe your feature

The landing-page for the documenatation should be improved.
Feel free to add some ideas to it @mikenikles 

### How to test

These changes will probably be on the docs-landing page

**Add testing steps when its clear how the page should look like**

**Comment by ChristinFrohne** [comment]
Awesome that you take care of this issue. Thanks, @Cahllagerfeld! 🧡

I created a [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=2631%3A865) so that the implementation will be easier. Let me know if you have any questions.

<img width="542" alt="Bildschirmfoto 2021-11-04 um 09 15 51" src="https://user-images.githubusercontent.com/46345125/140279872-d183ba0b-d829-4d8e-aa0e-900c6549acc7.png">
<img width="142" alt="Bildschirmfoto 2021-11-04 um 09 15 57" src="https://user-images.githubusercontent.com/46345125/140279879-5aae4f5c-dbc6-451e-bce6-4d947e028d0f.png">
