### ISSUE TITLE
Atom/RSS feed for www.gitpod.io/blog

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#1234]
Requested at https://twitter.com/Case/status/1458221941953744896?s=20

**Comment by case** [comment]
Thanks!

**Comment by mikenikles** [comment]
@Cahllagerfeld and I will collaborate on that on a live stream next week. Details TBD.

**Comment by mikenikles** [comment]
We attempted to implement that in #1254, but weren't able to complete the work due to an issue with how we wanted to parse the blog post content in the `src/hooks.ts` file. We narrowed it down to the `mdsvex` layout that causes problems.

This needs to be investigated more thoroughly. When doing so, please review the code in #1254 as a starting point for further exploration.

**Comment by bwklein** [comment]
@mikenikles I discovered this issue myself when trying to build a JSON search index file that includes content from MD files though MDsveX layouts.  Similar broken state when using the .render() function in the endpoint.

I found the video of the live stream from November last year and realized I was chatting during it.  At that time I didn't need to solve the problem you faced then, but NOW I do and am stuck.

Did you find out anything else about this issue since then?  How can we get the rendered content (HTML) from the markdown files in an endpoint?  

Here is my code and error...

![image](https://user-images.githubusercontent.com/12104446/166636382-bdab6fd2-de54-499b-beca-d90e2b18db5f.png)

**Comment by Cahllagerfeld** [comment]
Hey @bwklein 👋 
We couldn't resolve that issue unfortunately and put it on hold.
I just realized that the branch, we worked on for this feature got deleted, so I don't have the source code anymore.
Another idea, that came to my mind is using the `compile`-function MDSvex provides to turn the content from the `.md`-files to actual html. I just made the following snippet quite quickly. It's just an idea, not validated or tested though😬
```ts
import RSS from "rss";
import fs from "fs";
import path from "path";
import { compile } from "mdsvex";

const loadBlogPosts = async () => {
  const posts = await Promise.all(
    Object.entries(import.meta.glob("/src/routes/blog/*.md")).map(
      async ([filePath, page]) => {
        const { metadata } = await page();
        const filename = filePath.split("/").pop();
        const importedPage = fs
          .readFileSync(path.join(process.cwd(), filePath))
          .toString("utf-8");
        const html = await compile(importedPage); //compile takes in the config-object from MDSvex as second arg
        return { ...metadata, filename, html };
      }
    )
  );
```
