### ISSUE TITLE
Address Lighthouse Reports

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#135]
Run a Lighthouse report on all pages and address the suggestions.

**Comment by nisarhassan12** [comment]
@mikenikles For the permalinks within the blog and docs pages Lighthouse audit **Links do not have a discernible name** fails. I was wondering would it be worth the effort to add the title of the headlines as an aria-label on the link via writing some sort of remark plugin ? Thanks

**Comment by nisarhassan12** [comment]
Lighthouse audit Tap targets are not sized appropriately fails for some links on the privacy page probably those that are within a list maybe because the items are too close to each other. @ChristinFrohne It is not practical but it won't be feasible to increase the space between the list items only here? right ? 
![image](https://user-images.githubusercontent.com/46004116/128076464-824c4ba9-1b03-4835-9796-704e0ed83b12.png)

**Comment by ChristinFrohne** [comment]
>It is not practical but it won't be feasible to increase the space between the list items only here? right ?

It's the same spacing that we use elsewhere as well, right? Then I don't see why it needs to be changed only here. 
If you don't find any other explanation, go ahead and try adjusting the spacing as long as it only affects the privacy page.

**Comment by nisarhassan12** [comment]
https://github.com/gitpod-io/website/issues/135#issuecomment-890566454 is Fixed in https://github.com/gitpod-io/website/pull/881

**Comment by ChristinFrohne** [comment]
> We are gonna wait on this until #135 is closed. (see #731 )

What's the status here @nisarhassan12 ? Can we close this issue and open new ones more specifically for further improvements?

**Comment by nisarhassan12** [comment]
Thanks. Yeah Let's close this one as we already have more specific ones in place such as https://github.com/gitpod-io/website/issues/155 https://github.com/gitpod-io/website/issues/648
