### ISSUE TITLE
broken card layout on /community

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1355]
The spacing between the cards should always be the same. I think we agreed on using 16px between cards @nisarhassan12 
<img width="1323" alt="Bildschirmfoto 2021-12-10 um 12 13 24" src="https://user-images.githubusercontent.com/46345125/145565821-58fda9af-c9e3-48f4-a91c-1864d4105955.png">

**Comment by nisarhassan12** [comment]
Thanks, @ChristinFrohne for bringing this up. 

> I think we agreed on using 16px between cards 

Oh Sorry looks like there was a misunderstanding from my side I thought it was only meant to be 16px in the y-direction between the cards on mobile devices. 

Just to confirm Should I make it `16px` everywhere globally between the cards in both x and y directions including the areas listed below? Fixing the spacings in the y-direction between the cards is easier but making sure that it is always 16px is a bit complex.

For instance between the tweets it is 24px

<details>
<summary>
 Screenshot
</summary>
<img src="https://user-images.githubusercontent.com/46004116/145572085-eb693f88-18e5-473d-8c35-bc80831685ff.png">
</details>

Between the get started cards on Desktop it is not `16px` i.e it varies depending on the screen size and on mobile it is 32px(which is intentional from me as 16px looks fine for smaller cards but for the cards of this size 16px looks a bit tighter in my opinion)

| 16px | 32px |
| - | - |
| ![image](https://user-images.githubusercontent.com/46004116/145572749-7181e4b6-0d1b-4141-8bd6-8e29767ab265.png) | ![image](https://user-images.githubusercontent.com/46004116/145572802-d6e747b3-257c-4e59-a79f-3f8bbff69531.png) |

In some places such as the Helpful Resources section, we use 48px between the cards in the y-direction and in the x-direction it is varies depending on the screen size which helps with fluid web design. 

<details>
<summary>
 Screenshot
</summary>
<img src="https://user-images.githubusercontent.com/46004116/145577332-77e80c26-fb23-4e38-92fa-763355c89ad9.png">
</details>

**Comment by ChristinFrohne** [comment]
It doesn't have to be always 16px and it can vary with the responsive design. But always using 16px on Desktop for that card style should work fine. If we use the same style on /support then we should update the spacing to 16px there as well. The other sections (screenshots) can stay as they are :)

**Comment by nisarhassan12** [comment]
I have fixed this in #1349 
![image](https://user-images.githubusercontent.com/46004116/145962716-8c303672-62d4-43f9-b0e5-3fa3539839cf.png)

**Comment by nisarhassan12** [comment]
Fixed in #1349
