### ISSUE TITLE
the search on /support  should search the whole website not just the docs

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1426]
the search bar on https://www.gitpod.io/support should list search results from the whole website not just from docs.

**Comment by mikenikles** [comment]
We currently use an Algolia plugin called DocSearch (https://www.algolia.com/ref/docsearch/) which is free for technical documentation.

If we want to provide search for the entire website, we'll need to implement the Algolia product which comes with a price tag (https://www.algolia.com/pricing/).

@jakobhero, I don't think we currently capture metrics on how many search queries we serve monthly. Is this something you could help us add?

With that data, we can make an informed decision as to how much we'll have to pay for Algolia - if anything at all, since there's a free tier.

**Comment by chrifro** [comment]
**To be resolved:**
- do we track search queries by now?
- how much would the upgrade cost? 

If we decide to implement the global search, we should add it to the footer as well. You can ping me for the design. 

See related [Slack discussion ](https://gitpod.slack.com/archives/C01KGM9ETU6/p1664095088261679)

**Comment by Siddhant-K-code** [comment]
the solution, for now, is to improve the footer navigation (#2816) and enable searches on individual pages like `/guides` instead
