### ISSUE TITLE
Document IDE approaches (browser vs desktop vs local companion)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#1478]
Users have asked [[1](https://discord.com/channels/816244985187008514/905926786339188746/931470192435953724)] what is the preferred desktop flows between the different solutions, e.g.

1. Local companion
2. VS Code command pallette
3. The user configurations

We could do with some general documentation discussing browser vs desktop IDE setups. 

Related [[1](https://www.jetbrains.com/help/idea/2021.3/remote-development-starting-page.html)][[2](https://github.com/gitpod-io/website/pull/1225/files)]

**Comment by AntonyMilneQB** [comment]
Thanks very much for making this issue! Just to clarify, I am very grateful for the current documentation which is very useful, but also I did find it confusing trying to figure out exactly how what I should be doing.

As a user who doesn't understand the technicalities behind desktop IDE access to gitpod I'm generally looking for instructions that give me a setup that just works. So posts [like this](https://www.gitpod.io/blog/local-app) announcing a new feature I don't really understand don't make it clear to me whether I should be using that feature or not. [This note](https://www.gitpod.io/docs/develop/local-companion#connect-to-your-local-vs-code) is very useful since it makes it clear that if I don't know what I'm doing, I should just stick to VS Code desktop and ignore local companion.

Similarly with Jetbrains IDEs, I ended up [here](https://github.com/gitpod-io/template-jetbrains-pycharm) and didn't know whether it's the recommend workflow or completely obsolete. There's various links to [this page](https://youtrack.jetbrains.com/issue/IDEA-226455) also, and I don't know whether I should be reading through them and trying to do what they suggest, or if that's just something for the future.

Overall it would be super helpful if it were just a bit clearer what the recommended workflows are, and when I might want to deviate from that recommended workflow. Perhaps this would mean updating old announcements if they are no longer the cutting edge way of doing things or making it clear which solutions are now redundant.
