### ISSUE TITLE
Update workspace cube image

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1571]
![workspace-jetbrains-new-arrangement](https://user-images.githubusercontent.com/46345125/152959902-6198b854-b9d5-4bea-82ee-10354c6a1e98.png)

**Comment by ChristinFrohne** [comment]
@nisarhassan12 do I need to watch out for anything when swapping out this image? In which folder is the current image? I couldn't find it.

**Comment by nisarhassan12** [comment]
Thanks, @ChristinFrohne for looking into this. 

> do I need to watch out for anything when swapping out this image?

Yes, make sure the image when exported does not have any whitespace in it like the current one that we have in prod https://www.gitpod.io/images/illustration-large.jpg otherwise it would look scaled-down.

Also, make sure to optimize it maybe we https://tinypng.com  and maybe export a smaller version of it as the one you shared above has a size of 4.1MB which can significantly impact the site speed i.e the [current one](https://www.gitpod.io/images/illustration-large.jpg) has a small size 323KB. 

> In which folder is the current image?

It's in `/static/images/` and the name is `illustration-large.jpg` You can press `CMD + P` and then type in `/static/images/illustration-large.jpg` it will show the image in Gitpod then you can name the image `illustration-large.jpg`. 

Now if it is a png then you would also have to change it here on this ling to `.png`:

https://github.com/gitpod-io/website/blob/092583eda1eb47b051c52964c7bac6f6ac950ca9/src/lib/components/index/hero.svelte#L178


Let me know if you want help with anything. I can takeover this as well if you like.

**Comment by nisarhassan12** [comment]
Closing this as the new cube image has been added.
