### ISSUE TITLE
Forum and support email not working

### ISSUE THREAD

**Issue by julkhami** [gitpod-io/website#1656]
### Bug description

I am unable to send emails in the support form or post to the community forum. It has been this way for 24 hours.

Does anyone know what’s going on?

Thank you

### Steps to reproduce

Submit message to support or post to forum

**Comment by pawlean** [comment]
Hi @julkhami! I think that there is an ongoing issue with the form. Looks like[ this is the root cause.](https://twitter.com/mikenikles/status/1496130705394438159)

Regarding the forum, it is currently read-only. Our community hangs out mostly over on [Discord](https://www.gitpod.io/chat). You're welcome to join us there!

**Comment by mikenikles** [comment]
Thanks @julkhami for reporting that. We're in contact with our hosting provider's support team to investigate what causes the exceptions on their end.

In the meantime, you can email us directly at contact@gitpod.io. My apologies for the inconvenience.
