### ISSUE TITLE
SEO: Avoid enormous network payloads

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1685]
Large network payloads are highly correlated with long load times. They also cost users money; for example, users may have to pay for more cellular data. So, reducing the total size of your page's network requests is good for your users' experience on your site and their wallets. [[1](https://web.dev/total-byte-weight/#:~:text=Large%20network%20payloads%20are%20highly,your%20site%20and%20their%20wallets.)]

[affected pages](https://docs.google.com/spreadsheets/d/1uuxfBXe_FoAUTbrKs3A_J5pKfAfmsf1g85aFjJ8XJ7k/edit#gid=0)

**Comment by Cahllagerfeld** [comment]
I'm currently playing around with [ImgBot](https://imgbot.net/) in one of my repos, to set it up properly.

**Comment by Cahllagerfeld** [comment]
It looks like the bot is still active, and frequently requests compression for the our repo. Nontheless it might be confused due to the renaming of the repo. Agreed with Mike yesterday, to remove the app and re-add it. We're depending on one of the admins for this though. Mike took care of contacting the admin. I'll go ahead with this, once I get info that the Bot got readded.

Once added the bot should open a PR for optimizing ALL of our current images.
<img width="1280" alt="grafik" src="https://user-images.githubusercontent.com/43843195/160550472-dac116ec-d347-4cf5-a416-23dc3f8d88c3.png">

**Comment by chrifro** [comment]
Is this still relevant? cc @Cahllagerfeld @Siddhant-K-code ?

**Comment by Siddhant-K-code** [comment]
Thinking these (#2900 #2862 #2758) in mind. I don't think other things we can do. One thing I am planning to migrate all `PNGs` to `WEBp` files & also #2921 . for optimal which also improves the Mobile Performance

**Comment by Cahllagerfeld** [comment]
In general, I think this issue is still relevant. Nonetheless, it's like a collection of things that could be done to reduce the initial payload:

- Optimize images => compress, adjust dimensions, format, ...
- Implement lazy-loading for images that aren't in the viewport when loading them initially => jacob did this for the changelog
- ...

We should define a definition of done for this issue, so we know when to close (or when not).

**Comment by Cahllagerfeld** [comment]
As we took action on this already and implemented a couple of things for fixing this, I'd close the issue for now, and reopen an follow-up item in case we need to make further adjustments in the future 👍

**Comment by Siddhant-K-code** [comment]
It will be resolved with #2923 as a sub-issue of https://github.com/gitpod-io/website/issues/1463
