### ISSUE TITLE
update icon style

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2022]
we have a new icons style: 🥳
<img width="599" alt="Bildschirmfoto 2022-05-11 um 15 50 28" src="https://user-images.githubusercontent.com/46345125/167865863-54c75426-861e-4190-9124-477d8c4ca872.png">

[Figma](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A1119)

When implementing it, we need to watch out that the icon style remains consistent. It might be that we have to create a few more icons with the new style. Please let me know if you see any places where they don't work well yet. cc @nisarhassan12 I will open some follow-up issues as well

**Comment by nisarhassan12** [comment]
@chrifro 2 places I found where we need a new icon style: 

- [ ] 1 - On the community heroes page under your benefits section for the beta access icon i.e does not fit with the rest of the gradient icons so that is why we need a new icon here. 
![image](https://user-images.githubusercontent.com/46004116/168473362-8f318354-f5b8-4c08-8d41-9584c5296acf.png)
For now I have replaced it with the new gradient file icon. 
![image](https://user-images.githubusercontent.com/46004116/168473248-9f85e194-f9e9-4e3f-b13f-c95462f47ada.png)

- [ ] 2 - The icons at the bottom of the Extension activation page i.e they don't fill well with the new gradient style of the icons. 

![image](https://user-images.githubusercontent.com/46004116/168473497-3891843c-96a0-44ff-941e-6d3c027176d3.png)


Other icons are updated in https://github.com/gitpod-io/website/pull/2043

**Comment by chrifro** [comment]
>1 - On the community heroes page under your benefits section for the beta access icon i.e does not fit with the rest of the gradient icons so that is why we need a new icon here.

Please use the following icons: [[1](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=2625%3A396)]
<img width="761" alt="Bildschirmfoto 2022-05-16 um 09 16 27" src="https://user-images.githubusercontent.com/46345125/168539084-2088cdbb-fb1a-41eb-a40d-5cdd0ecc5023.png">

Note: in case you missed it in another PR, the cards still have a shadow style. 


>2 - The icons at the bottom of the Extension activation page i.e they don't fill well with the new gradient style of the icons.

Please use the following icons: [[1](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=1095%3A105)]
<img width="499" alt="Bildschirmfoto 2022-05-16 um 09 21 54" src="https://user-images.githubusercontent.com/46345125/168539885-22fb3499-5c56-4b93-b2cb-35d5148649ee.png">

**Comment by nisarhassan12** [comment]
@chrifro I have also updated `/security/thanks` to use the new heart icon i.e atm it uses an outlined version which is not in the component library

![image](https://user-images.githubusercontent.com/46004116/168558586-c2ac703f-1e20-4a0f-907d-be9f7186549c.png)
