### ISSUE TITLE
Update IDE screenshots

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2069]
@nisarhassan12 could you check on the screenshot images? Some of them have a black outline. 🙏

You can find the images [here](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=4328%3A3489)
<img width="708" alt="Bildschirmfoto 2022-05-16 um 15 03 52" src="https://user-images.githubusercontent.com/46345125/168598988-1af699fe-a998-4e53-a894-4e514582fe3c.png">

**Comment by nisarhassan12** [comment]
> Some of them have a black outline. 🙏

@chrifro I'm already using the images you linked the problem is the images with black outlines have whitespace as part of the export. I think that is to make sure that their height and widths are consistent. 
![image](https://user-images.githubusercontent.com/46004116/169744505-b1fd923a-a176-4f6f-a3ac-ebd27084a434.png)

I tried cropping that whitespace off myself but then they become inconsistent in size resulting in layout shifting beneath. Can you make it so that all the images have the same size without any whitespace as part of the image? Thanks

**Comment by chrifro** [comment]
Should be fixed now @nisarhassan12 
https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=4328%3A3489

**Comment by nisarhassan12** [comment]
Thanks, @chrifro I have updated the Go land image and not it works fine see the preview here https://github.com/gitpod-io/website/pull/2109

The other 2 screenshots where there is a very slight small stroke are the VS code desktop and Browser screenshots. The link you shared does not have the VS Code browser screenshot and also for some reason I'm not able to get rid of the shadow from the VS Code Desktop image. Can you adjust that? Thanks.
