### ISSUE TITLE
Integrate WebPageTest into our CI pipeline

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#214]
See https://github.com/WPO-Foundation/webpagetest-github-action

**Comment by nisarhassan12** [comment]
Hey Mike what do you think about adding https://github.com/GoogleChrome/lighthouse-ci instead of this? i.e Lighthouse CI is free while this is not free i.e we need to have a subscription for the WPO API secret key. 
![image](https://user-images.githubusercontent.com/46004116/119367416-5b3c6600-bccb-11eb-91bb-2a525cf55e7f.png)

**Comment by mikenikles** [comment]
👍 For Lighthouse CI. We want to set it up so that the tests run against the Netlify deploy URL for each PR.

**Comment by nisarhassan12** [comment]
Closing this in favour of #522 From what I understand we don't need to integrate WebPageTest Lighthouse CI will do the job. Please re-open If I misunderstood something.
