### ISSUE TITLE
[docs] Images show with white background

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/website#237]
Did anyone change something regarding image processing on the website recently? The transparent backgrounds on the images in the docs are all white now.

**Comment by svenefftinge** [comment]
<img width="839" alt="Screenshot 2019-07-24 at 11 13 57" src="https://user-images.githubusercontent.com/372735/61781176-2a0b5a00-ae04-11e9-9774-28cd7b2bb241.png">

**Comment by nisarhassan12** [comment]
I have found using git bisect that the problem was due to an upgrade of dependency "gatsby-image". Thanks! a lot @jankeromnes for guiding about How to resolve regression.
commit: ` a249c2eacd5b9bca8dc1e8445eb2c8c7d863a1e5`
![image](https://user-images.githubusercontent.com/46004116/61789084-37890a00-ae2d-11e9-9220-89b1a9035ba2.png)

**Comment by svenefftinge** [comment]
Thanks!
