### ISSUE TITLE
New media image

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#240]
Currently, the media image is cut in tweets. 

Current look:
<img width="541" alt="Bildschirmfoto 2019-07-30 um 10 29 58" src="https://user-images.githubusercontent.com/46345125/62113501-025d3b80-b2b5-11e9-8d60-e352b73150c9.png">

New design::
![Media-image-new](https://user-images.githubusercontent.com/46345125/62114116-3edd6700-b2b6-11e9-8de3-50a27d9f7c11.jpg)

**Comment by jankeromnes** [comment]
I'm wondering if the word "Online" is really necessary:

```
One-Click IDE for GitHub
```

"One-Click" already implies that it opens quickly and that you don't need to install/configure complicated stuff, and "GitHub" is already known to be an online platform.

**Comment by jankeromnes** [comment]
Also, the word "online" itself is starting to show its age (reminds a lot of AOL). I don't think any of the cool new web services today call themselves "online".

**Comment by ChristinFrohne** [comment]
I agree that it doesn't sound smooth and it's probably obvious that it's online. The reason why we changed it to `one-click online IDE` is that  `online` should be included for SEO reasons in h1 if `online IDE`is one of our main keywords. 
For the media image I just continued with it to be consistent. But I can also leave it out, as it's obvious and doesn't have any effect on SEO here.

**Comment by jankeromnes** [comment]
According to Google Search Console, in terms of clicks, our top keywords are `gitpod` (overwhelmingly) then `git pod`, `github ide`, followed by `online ide`:

<img width="600" alt="Screenshot 2019-07-30 at 12 17 08" src="https://user-images.githubusercontent.com/599268/62121782-a8647200-b2c4-11e9-8888-8e329d4c6139.png">

(And if you sort by impressions, which I think is less relevant, you get the top keywords `io`, `gitpod`, `online ide` followed by `github ide`.)

---

Then, according to [Alexa](https://www.alexa.com/siteinfo/gitpod.io), our top keywords by search traffic are `gitpod` (overwhelmingly), followed by `git pod`, `gitpod chrome extension`, `github ide`, and only then `online ide`:

<img width="450" alt="Screenshot 2019-07-30 at 12 14 13" src="https://user-images.githubusercontent.com/599268/62121281-959d6d80-b2c3-11e9-87db-047569c2e647.png">

Alexa also suggests we should do better on keywords like `cloud ide`, `vscode cloud`, `vscode online` and `visual studio code online`, because they currently don't take anyone to Gitpod, even though they could:

<img width="450" alt="Screenshot 2019-07-30 at 12 26 27" src="https://user-images.githubusercontent.com/599268/62122144-56701c00-b2c5-11e9-966a-dbbeabfbe177.png">

It also says we could easily rank well under `coding interview tool`, if we tried.

**Comment by ChristinFrohne** [comment]
If you just look at the last 28 days, `online IDE`is already on the second place. Maybe that correlates with the changes of the headline

**Comment by jankeromnes** [comment]
> If you just look at the last 28 days, `online IDE` is already on the second place. Maybe that correlates with the changes of the headline

Aha, indeed:

<img width="912" alt="Screenshot 2019-07-30 at 13 03 11" src="https://user-images.githubusercontent.com/599268/62124411-6ccca680-b2ca-11e9-8cfb-95696edadd65.png">

Seen from another angle, my gut feeling here is that keywords with a high click/impression ratio are "higher-quality" keywords -- i.e. when people see it, they also find out result relevant enough to click on it.

Here are the same keywords again, sorted by "quality" or "relevance" (i.e. clicks/impressions):

| keyword | clicks | impressions | relevance |
| --- | --- | --- | --- |
| gitpod | 2398 | 3293 | 72% |
| gitpod.io | 46 | 65 | 70% |
| git pod | 116 | 170 | 68% |
| github online ide | 43 | 67 | 64% |
| git online editor | 35 | 64 | 54% |
| github ide | 154 | 492 | 31% |
| github online editor | 43 | 140 | 30% |
| online ide | 194 | 3664 | 5% |
| ide online | 37 | 963 | 3% |
| io | 76 | 5887 | 1% |

**Comment by svenefftinge** [comment]
@jankeromnes doesn't all that only mean that we haven'T optimized our website for 'online ide'?
If we want to get bette rin SEO we need to identify the keywords first and optimize for them (and gitpod is obviously not one of them)
