### ISSUE TITLE
Add "Early Access" release label for workspace classes and usage-based billing

### ISSUE THREAD

**Issue by jldec** [gitpod-io/website#2682]
Followup to #2657

Using the `Beta` label for early access feature releases is not ideal because

1. Early access releases are more like `Alpha` releases, with changes in design likely based on feedback.
2. Users who see `Beta` in the menu may be disappointed or may miss the text which says "available by invitation only" in the page banner.

 ### proposal
 - add a new label `Early Access` for workspace classes and usage-based billing.
 - describe this label in the [releases page](https://www.gitpod.io/docs/references/gitpod-releases) before `Alpha` and `Beta`.

> **Early Access** - Available by invitation to gather user feedback -- changes likely.

(_@jldec edited wording and removed CSS wrapping ssue on Sep 10._)

**Comment by gtsiolis** [comment]
For the label, instead of Early Access we could use **Limited Availability (LA)** and use the `LA` acronym similar to `GA` for the **[General Availability (GA)](https://en.wikipedia.org/wiki/Software_release_life_cycle#:~:text=for%20the%20web.-,General%20availability%20(GA),-%5Bedit%5D)**. In any case, **[Early Access](https://en.wikipedia.org/wiki/Early_access)** still sounds good and is commonly used.
