### ISSUE TITLE
Place Get a Demo button on Pricing Pages (SaaS & Self Hosted)

### ISSUE THREAD

**Issue by Thomas-Gitpod** [gitpod-io/website#2779]
On this [Page](https://www.gitpod.io/pricing) & this [Page](https://www.gitpod.io/self-hosted)

Please place a "Get a Demo" button prominently below the plans boxes and above the "Can’t find the answer here? Please Contact Sales".

In its current state the "Get a Demo" buttons are hard to find and this would benefit the traction on people self serving with demos.

Could you also make it bright orange please?

**Comment by anitapetersen** [comment]
This would be super nice ;) Hypothesis: People are clicking on pricing first before getting in contact with us.

**Comment by Siddhant-K-code** [comment]
> Could you also make it bright orange please?

I think, that's not required.
Regarding this, @chrifro will have some more context.

**Comment by Siddhant-K-code** [comment]
is this better (section reorder wise)?

![image](https://user-images.githubusercontent.com/55068936/191935708-7103baef-9e6c-4d32-bbb8-d67e8585d164.png)

**Comment by Thomas-Gitpod** [comment]
I think that could work! It just has to be seen prominently and without any scrolling, like from the basic perspective when you land on the page. I think that could already boost the use of "Get a Demo"

**Comment by Siddhant-K-code** [comment]
We have to take a final approval from @chrifro before implementing the above.

**Comment by chrifro** [comment]
>In its current state the "Get a Demo" buttons are hard to find and this would benefit the traction on people self serving with demos.

FYI, @Thomas-Gitpod new users always see "get a demo" button in the top navigation. It only changes to "dashboard" once you are logged in.
<img width="368" alt="Bildschirmfoto 2022-09-23 um 15 43 12" src="https://user-images.githubusercontent.com/46345125/191974653-db867ff2-ae39-4baa-afcf-c623b7194759.png">
Still I agree that we could have a more prominent "Get demo" button. I will look into it

>is this better (section reorder wise)?

@Siddhant-K-code thanks for looking into it, but that solution wouldn't solve the problem. Also, the Get-started box is an element that is only used at the end of a page.

I will create a mockup for it

**Comment by phimae** [comment]
A "Get Demo" button somewhere on the pricing options definitely makes sense imo. Even if it's just added in the "Can’t find the answer here? Please contact sales or **get a demo**.

**Comment by Siddhant-K-code** [comment]
@chrifro I think we can focus on 🛹 solution for this :shipit:  and we can iterate & optimize it later. WDYT?

**Comment by chrifro** [comment]
>Hey Christin! Any updates on this?


hi @Thomas-Gitpod, sorry for not getting back to you earlier. There are several open discussions in Notion on how to generally improve the pricing pages [[1](https://www.notion.so/gitpod/Update-self-hosted-pricing-page-with-detailed-features-overview-20ff7da33b8f470889e1d0e731819ffd)] [[2](https://www.notion.so/gitpod/Update-pricing-information-on-website-556103fb92cf44369bddabec0a7d81e2)]. That's why this got paused. But let's do an easy skateboard solution to add a "get demo" button. 

**Suggestion:**
<img width="722" alt="Bildschirmfoto 2022-10-19 um 09 55 49" src="https://user-images.githubusercontent.com/46345125/196630943-b7664de3-d538-4a91-9754-f3e694a5c611.png">

view [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=4999%3A6840)

If there are no opposing opinions on the design, I'd move it over to our issues that are prioritized for implementation 🏀

**Comment by Thomas-Gitpod** [comment]
That's perfect Christin!
