### ISSUE TITLE
Fix contrast on "Early Access" pill when selected

### ISSUE THREAD

**Issue by jldec** [gitpod-io/website#2996]
The orange text on pink when Early Access pages are selected is hard to read.
<img width="259" alt="Screenshot 2022-11-04 at 12 15 53" src="https://user-images.githubusercontent.com/849592/199970936-c5e6a7bd-0392-4f6a-8503-83225ea55320.png"> <img width="242" alt="Screenshot 2022-11-04 at 12 15 39" src="https://user-images.githubusercontent.com/849592/199970949-532d6773-7759-459a-9f85-aafcf1b62414.png">

**Comment by Siddhant-K-code** [comment]
I think, there may be a minor CSS loading issue & potentiality should be fixed by a reload 🙏🏼 . It appears like this currently: 

![image](https://user-images.githubusercontent.com/55068936/199971857-482ad425-f848-46cc-a9c5-0e5b0f9c0b20.png) ![image](https://user-images.githubusercontent.com/55068936/199971772-5ac21d48-d44b-4cd1-b4a1-8e872342e343.png)

**Comment by jldec** [comment]
Can't repro anymore :)
