### ISSUE TITLE
Add tags to each blog post

### ISSUE THREAD

**Issue by Siddhant-K-code** [gitpod-io/website#3021]
### Description

Instead of linking the most recent articles in `/blog`, we should add tags to each blog post and display the three most relevant ones. Related to https://github.com/gitpod-io/website/issues/1683

**Comment by chrifro** [comment]
**Context:**
High-potential URLs like older blog posts, don't receive many internal links. Instead of linking the most recent articles in /blog/xyz, we should add tags to each blog post and display the three most relevant ones. By that, we improve the SEO score for older blog pages. 
After reading a blog post, the user sees the three most recent blog posts in the “more articles” section. It would be a nicer experience for the user to get blog posts suggested that relate to the blog that they just read.


**Next steps:**
- [ ] add tags to existing blog posts `Company building`, `Engineering`, `Gitpod updates` & `Developer experience`. Lots of examples are listed in [this internal RFC](https://www.notion.so/gitpod/Add-context-tags-to-blog-posts-531edc2fbd8a4318b733137faf86bc15). Outdated blog posts should not get a tag
- [ ] add “sort by”-section to /blog (see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5885%3A10950&t=2NRvGOeHy7ErLWYP-1))
- [ ] rename “more articles” to “You might also like” on /blog/xyz
- [ ] introduce a flow/checkbox for new blog posts to always add a tag
- [ ] display 12 full blog post cards instead of 6 on /blog
