### ISSUE TITLE
[SEO] landing page improvements

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3063]
- [ ] Missing alt tag for [https://www.gitpod.io/indicator.svg](https://www.seobility.net/outbound/redirect.go?url=https%3A%2F%2Fwww.gitpod.io%2Findicator.svg&security=91d0468e290aee0f0a89a9c752829f2dde7da880)
- [ ] we have 30 headlines on the page. The amount of headings should be in a more proper relation to the amount of text. Can we remove the <hx> tags but keep the styling for 
`5h weekly productivity gain per engineer4x faster time from zero to first PR`
`61% cost savings compared to a VDI solution`
`+500k developers are using Gitpod`
`Select project, check dependencies, checkout branch, viewreadme.txt, install tools, run build, run test, check dependencies,checkout branch, viewreadme.txt, install tools,run build, run test, start...`
`Node or TypeScript` 
`Python`
` Golang`
` Rust`
`Java`
 `Svelte`

**Comment by Siddhant-K-code** [comment]
For the following ones, i don't think we should change it from `H` tags, because these are some headlines which should be indexed by crawlers (it prefers Header tags & do no crawl all description & body text):

- `5h weekly productivity gain per engineer4x faster time from zero to first PR`
- `61% cost savings compared to a VDI solution`
- `+500k developers are using Gitpod`

---

Will update the following in my PR:

- `Select project, check dependencies, checkout branch, viewreadme.txt, install tools, run build, run test, check dependencies,checkout branch, viewreadme.txt, install tools,run build, run test, start...`
- `Node or TypeScript` 
- `Python`
- ` Golang`
- ` Rust`
- `Java`
- `Svelte`
