### ISSUE TITLE
Add whitepaper sign-up component to for/customers and for/enterprise

### ISSUE THREAD

**Issue by MichaelAring** [gitpod-io/website#3328]
### Description

**Context**
[See internal task](https://www.notion.so/gitpod/Place-whitepaper-sign-up-component-across-website-35b13ae5baba47c783cccdc8d09b25c3)

**Suggestion**
Use the component from [/CDE](https://www.gitpod.io/cde)
<img width="736" alt="Screenshot 2023-01-30 at 20 01 55" src="https://user-images.githubusercontent.com/99804441/215570268-a5fafda0-cc9b-4af9-a725-ab2cf0cd8499.png">

...and implement it on:

1. [for/customers](https://www.gitpod.io/customers)
Add whitepaper component below "Trusted by 750k developers" component

2. [for/enterprise](https://www.gitpod.io/for/enterprise)
Replace "Get Demo" component at the bottom with whitepaper component

**Comment by Siddhant-K-code** [comment]
> [for/enterprise](https://www.gitpod.io/for/enterprise)
Replace "Get Demo" component at the bottom with whitepaper component

@MichaelAring Instead of replacing it, we could make it replicated as [`/CDE`](https://www.gitpod.io/cde):
Whitepaper Callout -> Get Started Callout

This^ would be handier for the users who don't want to scroll up to "Get a Demo" after the whitepaper download 😄
