### ISSUE TITLE
Align workspace messaging between dashboard and website

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3340]
|dashboard|website|
|-|-|
|<img width="359" alt="Bildschirm­foto 2023-01-31 um 15 15 38" src="https://user-images.githubusercontent.com/46345125/215786188-491cc619-d52a-406a-bb71-4ad55141d2de.png">|<img width="499" alt="Bildschirm­foto 2023-01-31 um 15 23 07" src="https://user-images.githubusercontent.com/46345125/215786353-e2c9e2e2-2664-49f2-b02a-4a048c13baba.png">|

@MichaelAring @gtsiolis any preferences on which naming convention we should follow? e.g. memory vs RAM

**Comment by Siddhant-K-code** [comment]
Since We are Developer focused products. We should consider first naming convention 😄

**Comment by MichaelAring** [comment]
I am in favor of
cores - RAM - storage

This is also used by [Codespaces](https://github.com/features/codespaces) to describe workspace sizes and, I think, general convention with best readability. We should specify CPUs in the docs.

<img width="839" alt="Screenshot 2023-02-01 at 12 36 46" src="https://user-images.githubusercontent.com/99804441/216032194-d5a52ec7-d009-4172-92e0-6c1744d9bdd5.png">

**Comment by gtsiolis** [comment]
+1 for using RAM and Storage terms.

Not entirely sure about the cores terms as vCPUs can describe something different, especially since we using containers and not VMs under the hood but seems to describe accurately enough what we offer. 💭 

I've opened https://github.com/gitpod-io/gitpod/pull/16153#pullrequestreview-1278968567 to update the descriptions in some test files and asked for some clarification in https://github.com/gitpod-io/gitpod/pull/16153#discussion_r1093122887. However, I believe these descriptions come directly from the database and we should update these there, thus opened the PR as a task placeholder.

We already use these terms in the [relevant docs](https://www.gitpod.io/docs/configure/workspaces/workspace-classes#:~:text=up%20to%204%20cores%2C%20up%20to%208GB%20RAM%2C%2030GB%20storage). Cc @MichaelAring 

Thanks @chrifro for opening this and caring about consistency! 🌮 🌮

**Comment by chrifro** [comment]
Awesome, thanks for following up on this @gtsiolis ✨

I'll then close this issue as the website wording will stay as it is and for the dashboard, changes will be picked up in #16153 🤝
