### ISSUE TITLE
Settings Sync instruction is not working anymore

### ISSUE THREAD

**Issue by alexanderv21** [gitpod-io/website#3931]
### Page URL

https://www.gitpod.io/docs/references/ides-and-editors/settings-sync#enabling-settings-sync-in-vs-code-desktop

### Description

Hi,

The _Settings Sync_ instruction is not working anymore in the latest VSCode build (>=1.8.1): I've followed the instruction to re-authenticate but the Gitpod authentication method is not there, even though the _configurationSync.store_ config is already created in user settings. I remember that my previous authentication process in the previous build is working just fine.

I think it's important to look at since maybe other users can't use the _Settings Sync_ function on Gitpod VSCode extension anymore.
Thanks!

**Comment by Siddhant-K-code** [comment]
Hey @alexanderv21 

Thanks for raising the issue. I've escalated this to the concerned team. 🙏

**Comment by johndunderhill** [comment]
We spent four hours trying to troubleshoot this while doing a new installation on a Mac last week.  We thought it was related to the installation process, but it's not: After the VS Code update, syncing no longer works.  We tried removing everything and re-installing and configuring from scratch, following the Gitpod documentation exactly, at least twice.  The only work-around for us was to manually copy the user settings to the web interface, and manually install the necessary extensions in both environments.  Now we have to manually keep them in sync.

While not particularly heavy, this was a non-trivial development environment, and the unexpected problem caused a considerable degree of confusion of and pain.  We just looked at the Microsoft PR that caused this, but we don't really understand what they did or why.  Sync is important to us.

**Comment by loujaybee** [comment]
Hey @johndunderhill / @alexanderv21. Thank you for the report. Since this repository is related to the GitHub Website, and there is already an [issue on the Gitpod repo](https://github.com/gitpod-io/gitpod/issues/18573) I'll link here and close this as a duplicate. The changes from Microsoft in VS Code also took us by surprise. When we realised the issue, we moved quick to [update our documentation](https://github.com/gitpod-io/website/pull/3933/files) with the workarounds, and [raised the issue above](https://github.com/gitpod-io/gitpod/issues/18573) to communicate and are now actively looking into resolving the issue. I'm sorry for the disruption, but do know that we are actively investigating and will communicate any other workarounds in the mean time on the other issue, again thank you for your patience 🙏
