### ISSUE TITLE
Introduce Guides

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#709]
I noticed an increasing number of teams and individuals who publish their experience with Gitpod. For example, [`ddev-gitpod`](https://github.com/shaal/ddev-gitpod) or some of the [DataStax examples](https://github.com/DataStax-Examples).

To better collect and showcase these, we need a new **Guides** section on our website. One of the key goals is for these guides to be written by our community, so we need to make this process as straightforward as possible and document it.

@ChristinFrohne could you help us with mockups for this 🙏?

Tasks
- [ ] Add the content from #740 as one of the initial guides

**Comment by ChristinFrohne** [comment]
Great idea! These are my thoughts, let me know what you think @mikenikles 

**Page integration:** We could add a link in the footer under "developer" and add a link to docs/references

This would be the overview of all existing guides include a CTA to submit a new guide at the bottom
<img width="361" alt="Bildschirmfoto 2021-07-06 um 10 44 40" src="https://user-images.githubusercontent.com/46345125/124570872-8cba5c80-de47-11eb-833a-9e24b8dea250.png">

The individual guide would look very similar to the blog posts, but also include the feedback widget 
<img width="362" alt="Bildschirmfoto 2021-07-06 um 10 52 09" src="https://user-images.githubusercontent.com/46345125/124572362-e2dbcf80-de48-11eb-98df-3ddbde0933a8.png">


Regarding guidelines to write these guides, it's probably best to document them publicly to keep support email as low as possible. I'll look into that next. 
FYI, [Vercel](https://vercel.com/guides) was a great example for the mockup, but they link to support instead of sharing guidelines publicly

**Comment by mikenikles** [comment]
This is brilliant, thank you Christin for putting that together!

Yes, I like the idea of documenting the guidelines publicly. How about we create a custom issue template in the gitpod-io/website repo and use the new form fields to guide people who want to create a new guide?
That issue template then includes instructions on how to create a new guide in the repo so anyone can open a PR, we can review & test & merge it.

@nisarhassan12 Could you get started with the implementation please for the two mockups Christin provided?

**Comment by nisarhassan12** [comment]
Yep. Sure I'll start working on it today.

**Comment by mikenikles** [comment]
For the URL pattern, how do you feel about this?
- `/guides`
- `/guides/hyphenized-title-of-guide`

**Comment by nisarhassan12** [comment]
Thanks. Mike what you suggested looks good to me.

**Comment by ChristinFrohne** [comment]
>How about we create a custom issue template in the gitpod-io/website repo and use the new form fields to guide people who want to create a new guide?
That issue template then includes instructions on how to create a new guide in the repo so anyone can open a PR, we can review & test & merge it.

Perfect. I was thinking to create a page explaining the guidelines with CTA to open a PR, but including everything directly in GitHub sounds even better. 

FYI, these are a few guides that I'm aware of. Some probably need an update. [Uno](https://platform.uno/blog/uno-platform-2-0-reloaded-gitpod-integration/), [Near](https://near.org/blog/near-onboarding-with-gitpod/), [Deepcode by Synk ](https://www.deepcode.ai/blog/syntax-versus-semantics-by-using-some-gitpod), [Hasura](https://marcopeg.com/2020/hasura-in-gitpod), [Helm Chart](https://jimmyb.ninja/post/1607011905/), [Docker](https://jimmyb.ninja/post/1624204526/), [NumPy](https://numpy.org/devdocs/dev/development_gitpod.html), [Tasmota](https://tasmota.github.io/docs/Gitpod/), [React](https://itnext.io/how-to-use-gitpod-in-your-create-react-app-based-project-dd4d0b33ce77), [Flutter](https://tianhaozhou.medium.com/gitpod-flutter-productivity-on-the-go-for-mobile-app-developers-cc2495049d52)

Let me know if there is anything else I can help with

**Comment by nisarhassan12** [comment]
Reopening this as the GitHub issue template is not implemented yet.

**Comment by ChristinFrohne** [comment]
Can you take over from here @mikenikles ?

**Outstanding to-do's:**
- create GitHub issue template
- review existing guides and contact authors if they would like to publish it 
- communicate the possibility to submit guides on Twitter

>FYI, these are a few guides that I'm aware of. Uno, Near, Deepcode by Synk , Hasura, Helm Chart, Docker, NumPy, Tasmota, React, Flutter (see links in the comment above)

**Comment by nisarhassan12** [comment]
The landing page for guides is live but hidden from Search Engines atm https://www.gitpod.io/guides We have https://github.com/gitpod-io/website/issues/800 to track that.

@mikenikles I have assigned you to this issue now so that you can take over the remaining todos as specified here https://github.com/gitpod-io/website/issues/709#issuecomment-891650587 Thanks

**Comment by mikenikles** [comment]
Post-Launch Checklist => https://github.com/gitpod-io/website/issues/1740

**Comment by mikenikles** [comment]
@ChristinFrohne Could you do me a favour and create two teaser images for the first guide with Appwrite? I'm looking for the following - but with the Appwrite logo:
- https://www.gitpod.io/images/guides/set-up-a-full-drupal-dev-environment-in-a-browser/teaser-image.png
- https://www.gitpod.io/images/guides/set-up-a-full-drupal-dev-environment-in-a-browser/teaser.jpg

**Comment by ChristinFrohne** [comment]
I opened a [new library for guide images](https://www.figma.com/file/gq1v6dj0rzs4tvJcFabKPy/Blog-%26-Changelog-images?node-id=503%3A35). Whenever you launch a new guide, you can simply swap the logo. Let me know if that works for you

**Comment by mikenikles** [comment]
:smiling_face_with_three_hearts: Excellent, yes this works very well. Thanks Christin!
