### ISSUE TITLE
Missing option to subscribe to the newsletter

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#82]
Possible location for a sign-up-button:

- in the app underneath the subscriptions 

- underneath the blog posts

**Comment by jankeromnes** [comment]
@nisarhassan12 if you have time, could you please look into this?

What we'd like is an `<input type="email">` with a `Subscribe` button that allows interested people to subscribe to our newsletter.

Also, it would be interesting to see if this HTML/JS widget can directly talk to MailChimp.com, so that we don't have to implement an email collection backend.

Could you please see if MailChimp offers HTML/JS "Subscribe" widgets, or if we can somehow post something to their API to do that (e.g. with a `<form>`)?

**Comment by ChristinFrohne** [comment]
Mailchimp has four different signup forms
<img width="1281" alt="Bildschirmfoto 2019-06-14 um 08 41 22" src="https://user-images.githubusercontent.com/46345125/59488811-d27ee380-8e80-11e9-9358-55e96b53b287.png">
