### ISSUE TITLE
About the i18n method

### ISSUE THREAD

**Issue by mouse484** [gitpod-io/website#96]
When I tried to translate the Gitpod site, I ran into the problem of the i18n method.

This problem arose from the story of creating a Japanese page (https://twitter.com/Esc_mouse_484/status/1120527320446590978) , but I think Gitpod is a useful tool that people in more languages ​​should use.

I need your help :joy:

(It may be incorrect English but I am sorry)

**Comment by jankeromnes** [comment]
Hi @mouse484, many thanks for offering to translate Gitpod! And also for opening this issue. 🙏

The problem is on our side: it seems that our website is not yet set up for internationalization. Thankfully, it seems that with Gatsby it would be relatively easy. We'll need to:

- [ ] install a Gatsby plugin for localization
- [ ] create a dictionary of strings to be localized
- [ ] convert all hard-coded strings in our website with a localized call

Here are two blog posts that explain how this can be done:
- https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/
- https://phraseapp.com/blog/posts/i18n-with-gatsby/

**Comment by mouse484** [comment]
I also thought about using a plug-in, but I couldn't do it because I did not have the knowledge of gatsby 😭 

I checked and found some ways
* i18next (react)
* react-intl
* Gatsby-plugin-i18n

 I can not choose

**Comment by jankeromnes** [comment]
It seems that both guides I found use `react-i18next`, so I think that's a pretty safe choice to pick.

`react-i18next`'s [quick start guide](https://react.i18next.com/guides/quick-start#install-needed-dependencies) suggests adding these packages to our `package.json`:

- `i18next`
- `react-i18next`

(Note: The blog posts I found also suggest installing these packages:

- `i18next-xhr-backend`
- `i18next-browser-languagedetector`
- `gatsby-plugin-i18next` (as a replacement to `i18next`, with a few extra features)

but maybe let's only install them if we really need them.)

**Comment by mouse484** [comment]
I have roughly understood about i18n.
I realized there was a need for major changes.

I"m not sure I can do it alone, so I would like to ask if you can help me.
