### ISSUE TITLE
[Docs Feedback]: add documenation howto whitelist gitpod for clipboard, popup,...

### ISSUE THREAD

**Issue by konne** [gitpod-io/website#985]
### Page URL

gitpod.io

### User feedback

Hi,

to have a really good developer experience in chrome it is important to allow for all gitpod domains.
Otherwise, you have to enable per workspace, again and again, clipboard, popup,,...
Please document howto to it by adding the right settings to chrome with [*.]gitpod.io 
as a general rule for all workspaces.

thx

**Comment by mikenikles** [comment]
Hi @konne 👋, great idea to document that. It's something that completely slipped my mind as I configured it many moons ago because it annoyed me 😄.

I documented clipboard and pop-up permissions in #990. You can [preview it here](https://deploy-preview-990--gitpod-kumquat.netlify.app/docs/configure/browser-settings) and if you have any feedback, I'd love to hear it.

Thanks

**Comment by konne** [comment]
Hi @mikenikles,

great docu and that you also did it for already for all browsers. Just make it publish.

bye
Konrad
